# Caution: this file may be regenerated by SOPC Builder.  User edits will be lost.
project_open -current_revision "D:/0Clare/DE2-70/Q80/DE2_70_NIOS_count_binary/DE2_70_NIOS_count_binary.qpf"
project_close